apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-docker
spec:
  selector:
    matchLabels:
      app: django-docker
  replicas: 2
  template:
    metadata:
      labels:
        app: django-docker
    spec:
      containers:
      - name: django-docker
        image: qnnakwue/django-docker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: django-docker
spec:
  selector:
    app: django-docker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort

