version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "
            python /usr/project/manage.py makemigrations &&
            python /usr/project/manage.py migrate &&
            python /usr/project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/project
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
